### ISSUE TITLE
maekula-piimamees example: excess videos

### ISSUE THREAD

**Issue by glensc** [smarbaa/yt-dlp-ugly-err#1]
> ## Download movie with two audio streams, 'et' and 'ru', all available
> ## subs and metadata and thumbnail and embed them all in a matroska container
> 
> $ yt-dlp -f 136+134+et+ru --audio-multistreams --video-multistreams --merge-output-format mkv --sub-langs all --embed-subs --embed-metadata --embed-thumbnail 'https://jupiter.err.ee/1608130759/maekula-piimamees'
> 

this created mkv with 3 video streams. how to keep only 1280x720?

<details><summary>streams dump</summary>

```json
{
  "video": [
    {
      "index": 0,
      "codec_type": "video",
      "codec_name": "h264",
      "width": 1280,
      "height": 720,
      "duration": "01:27:50.360000000",
      "tags": {
        "language": "eng"
      }
    },
    {
      "index": 1,
      "codec_type": "video",
      "codec_name": "h264",
      "width": 704,
      "height": 396,
      "duration": "01:27:50.360000000",
      "tags": {
        "language": "eng"
      }
    },
    {
      "index": 5,
      "codec_type": "video",
      "codec_name": "mjpeg",
      "width": 400,
      "height": 250,
      "duration": null,
      "tags": {
        "language": null
      }
    }
  ],
  "audio": [
    {
      "index": 2,
      "codec_type": "audio",
      "codec_name": "aac",
      "channels": 2,
      "channel_layout": "stereo",
      "tags": {
        "language": "est"
      }
    },
    {
      "index": 3,
      "codec_type": "audio",
      "codec_name": "aac",
      "channels": 2,
      "channel_layout": "stereo",
      "tags": {
        "language": "rus"
      }
    }
  ],
  "subtitle": [
    {
      "index": 4,
      "codec_type": "subtitle",
      "codec_name": "webvtt",
      "width": null,
      "height": null,
      "tags": {
        "language": "est",
        "title": null
      }
    }
  ]
}
```

</details>

**Comment by glensc** [comment]
I guess just omit it from the formats list :)

```
$ yt-dlp -F https://jupiter.err.ee/1608130759/maekula-piimamees
[ERRJupiter] Extracting URL: https://jupiter.err.ee/1608130759/maekula-piimamees
[ERRJupiter] 1608130759: Downloading JSON metadata
[ERRJupiter] 1608130759: Downloading m3u8 information
[info] Available formats for 1608130759:
ID  EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────
et  m4a audio only     │       m3u8  │ audio only        unknown    [et] Eesti
ru  m4a audio only     │       m3u8  │ audio only        unknown    [ru] Русский
134 mp4 704x396     25 │ 1118k m3u8  │ avc1.64001e 1118k video only 396p
136 mp4 1280x720    25 │ 1593k m3u8  │ avc1.64001f 1593k video only 720p
```

so, I want `-f 136+et+ru`.

maybe mention this help and usage in readme?

**Comment by smarbaa** [comment]
That's it. :-) Maybe I should mention it indeed.

**Comment by glensc** [comment]
your commit: https://github.com/smarbaa/yt-dlp-ugly-err/commit/16c9cccf50f992c4fc1c8ee6cc75dac90608f2b4 you suggest to download 1280x720 version, but i'm pretty sure it's upscaled from 704x396 version. and even 704x396 is upscaled from 528x396 by adding black borders at sides.

but what I did mean adding to readme, was to suggest to use `-F` flag to show formats and then decide what to download.

**Comment by smarbaa** [comment]
I never actually bothered to look at what that 720p actually contained. Sorry, that's what jupiter says, just checked it, I didn't modify it in any way. It is what it is and was meant as an example, a bad example, obviously. I'll think about that.
